# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/38939059-9ab6-4f1c-8969-6cc5318304e8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7221-4CAE";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home/sglre6355/games" = {
    device = "/dev/mapper/cryptdata";
    fsType = "btrfs";
    options = [ "subvol=games" ];
  };

  boot.initrd.luks.devices."cryptdata".device =
    "/dev/disk/by-uuid/cf3b5823-869d-48b0-8e33-315b665588c5";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
